[project]
name = "llm-evaluation-metrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.2.0",
    "evaluate>=0.4.3",
    "sentence-transformers>=3.4.0",
    "torch>=2.5.1",
    "transformers>=4.48.1",
]
